name: Deploy to Heroku
on:
  workflow_run:
    workflows: ["Test code quality"]
    types:
      - completed
    branches:
      - master
jobs:
  Deploy-to-Heroku:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Upload repository
      uses: actions/checkout@v3
    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
